// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzaWHF43tz5l0d8CbvoWcXxko0p2U3FwU',
    appId: '1:447868391025:web:919a394a094cb5e56655d0',
    messagingSenderId: '447868391025',
    projectId: 'lost-and-found-a3f6a',
    authDomain: 'lost-and-found-a3f6a.firebaseapp.com',
    storageBucket: 'lost-and-found-a3f6a.firebasestorage.app',
    measurementId: 'G-VKZMQZ4RJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6b2wE0os3FTxT7KsmBxA9-pRAeDgShr4',
    appId: '1:447868391025:android:bf316af6f41f7de66655d0',
    messagingSenderId: '447868391025',
    projectId: 'lost-and-found-a3f6a',
    storageBucket: 'lost-and-found-a3f6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfq1PRJ2cPA2Uib2IN8BmmxZxcCSjNJDU',
    appId: '1:447868391025:ios:15c03447ad3cea3c6655d0',
    messagingSenderId: '447868391025',
    projectId: 'lost-and-found-a3f6a',
    storageBucket: 'lost-and-found-a3f6a.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfq1PRJ2cPA2Uib2IN8BmmxZxcCSjNJDU',
    appId: '1:447868391025:ios:15c03447ad3cea3c6655d0',
    messagingSenderId: '447868391025',
    projectId: 'lost-and-found-a3f6a',
    storageBucket: 'lost-and-found-a3f6a.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzaWHF43tz5l0d8CbvoWcXxko0p2U3FwU',
    appId: '1:447868391025:web:20e729e7e0e2d8946655d0',
    messagingSenderId: '447868391025',
    projectId: 'lost-and-found-a3f6a',
    authDomain: 'lost-and-found-a3f6a.firebaseapp.com',
    storageBucket: 'lost-and-found-a3f6a.firebasestorage.app',
    measurementId: 'G-LW7TQ5E0ZL',
  );

}